const util = require("../resources/utilities.js");

// to be added; currently generated by ../resources/generate_template.js
module.exports = class Template {
  // constructor(filePath) {
  //   this.filePath = filePath;
  //   this.constants = [];
  //   this.entries = [];
  //   this.fields = [];
  //   this.entryFields = new Map();
  //   this.universalFields = new Set();
  //   this.entryConstraints = [];
  //   this.universalConstraints = [];
  //   this.resetPriorEntries = false;
  //   this.resetPriorFields = false;
  //   this.resetPriorEntryFields = false;
  //   this.resetPriorConstraints = false;
  //   this.built = false;
  // }
  //
  // async build() {
  //   let text;
  //   try {
  //     text = await util.readFile(this.filePath)
  //       .then(text => util.stripComments(text))
  //       .catch(e => { throw e; });
  //   } catch (e) {
  //     console.error(new Error(e));
  //     return null;
  //   }
  //
  //   const tokens = util.tokeniseText(text);
  //   const styleProperties = gatherStyleProperties(tokens);
  //   if (util.isEmptyTemplate(styleProperties)) { return null; }
  //   return util.serialiseTemplate(styleProperties);
  // }
  //
  // serialise() {
  //
  // }
  //
  // deserialise(json) {
  //
  // }
};
